apiVersion: v1
kind: Service
metadata:
  name: alert-collector-service
  namespace: safealert-app
spec:
  selector:
    app: alert-collector-service
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP
