# auth-service 전용 Secret
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: safealert-app
type: Opaque
stringData:
  db-password: "safealert123"
  jwt-secret: "safealert-jwt-secret-key-must-be-at-least-256-bits-long-for-hs256"
---
# api-gateway / notification-service 공유 JWT Secret
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: safealert-app
type: Opaque
stringData:
  secret: "safealert-jwt-secret-key-must-be-at-least-256-bits-long-for-hs256"
---
# subscription-service 전용 Secret
apiVersion: v1
kind: Secret
metadata:
  name: subscription-secrets
  namespace: safealert-app
type: Opaque
stringData:
  db-password: "safealert123"
