server:
  port: 8085

spring:
  application:
    name: subscription-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/subscription_db
    username: ${DB_USERNAME:safealert}
    password: ${DB_PASSWORD:safealert123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    com.safealert: INFO