apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-processor-service
  namespace: safealert-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alert-processor-service
  template:
    metadata:
      labels:
        app: alert-processor-service
    spec:
      containers:
        - name: alert-processor-service
          image: alert-processor-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8087
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka.safealert-infra.svc.cluster.local:9092
            - name: SPRING_DATA_REDIS_HOST
              value: redis-master.safealert-infra.svc.cluster.local
            - name: SPRING_DATA_MONGODB_HOST
              value: mongodb.safealert-infra.svc.cluster.local
