apiVersion: apps/v1
kind: Deployment

metadata:
  name: subscription-service
  namespace: safealert-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription-service

  template:
    metadata:
      labels:
        app: subscription-service
    spec:
      containers:
        - name: subscription-service
          image: subscription-service:latest
          ports:
            - containerPort: 8085

          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi

          env:
            - name: DB_HOST
              value: postgresql.safealert-infra

            - name: DB_USER
              value: safealert

            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: subscription-secrets
                  key: db-password

            - name: KAFKA_BOOTSTRAP
              value: kafka.safealert-infra:9092