architecture: standalone

auth:
  enabled: true
  rootPassword: "safealert123"
  username: "safealert"
  password: "safealert123"
  database: "event_store"

persistence:
  enabled: true
  size: 5Gi

resources:
  requests:
    memory: "512Mi"
    cpu: "200m"
  limits:
    memory: "1Gi"
    cpu: "500m"
