apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: safealert-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresql.safealert-infra.svc.cluster.local:5432/notification_db
            - name: SPRING_DATASOURCE_USERNAME
              value: safealert
            - name: SPRING_DATASOURCE_PASSWORD
              value: safealert123
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi